// actionTypes.js
export const FETCH_CITYNAME_REQUEST = 'FETCH_CITYNAME_REQUEST';
export const FETCH_CITYNAME_SUCCESS = 'FETCH_CITYNAME_SUCCESS';
export const FETCH_CITYNAME_CLEAR = "FETCH_CITYNAME_CLEAR";
// export const FETCH_FLIGHTNAME_FAILURE = 'FETCH_FLIGHTNAME_FAILURE';
