export const ONE_WAY_EMT_REQUEST = "ONE_WAY_EMT_REQUEST";
export const ONE_WAY_EMT_SUCCESS = "ONE_WAY_EMT_SUCCESS";

export const CLEAR_ONEWAY_EMT_REDUCER = "CLEAR_ONEWAY_EMT_REDUCER";
export const ONE_WAY_EMT_CLEAR_ALL = "ONE_WAY_EMT_CLEAR_ALL";
