export const BALANCE_SUBTRACT_REQUEST = 'BALANCE_SUBTRACT_REQUEST';
export const BALANCE_SUBTRACT_SUCCESS = 'BALANCE_SUBTRACT_SUCCESS';
export const BALANCE_SUBTRACT_FAILURE = 'BALANCE_SUBTRACT_FAILURE';