export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_CLEAR="SIGNUP_CLEAR"
export const ONBORDING_REQUEST="ONBORDING_REQUEST"