export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS";
export const ADMIN_AUTH_REQUEST = "ADMIN_AUTH_REQUEST";
export const ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL";
export const ADMIN_AUTH_LOG_OUT_REQUEST = "ADMIN_AUTH_LOG_OUT_REQUEST";