export const CREATE_PACKAGE_REQUEST = "CREATE_PACKAGE_REQUEST";
export const CREATE_PACKAGE_SUCCESS = "CREATE_PACKAGE_SUCCESS";
export const CREATE_PACKAGE_FAILURE = "CREATE_PACKAGE_FAILURE";
export const CLEAR_PACKAGE_REDUCER = "CLEAR_PACKAGE_REDUCER";