export const SUBADMIN_LOGIN_SUCCESS = "SUBADMIN_LOGIN_SUCCESS";
export const SUBADMIN_LOGOUT_SUCCESS = "SUBADMIN_LOGOUT_SUCCESS";
export const SUBADMIN_LOGIN_REQUEST = "SUBADMIN_LOGIN_REQUEST";
export const SUBADMIN_LOGIN_FAILURE = "SUBADMIN_LOGIN_FAILURE";