export const HOTEL_REQUEST_GRN = "HOTEL_REQUEST_GRN";
export const HOTEL_SUCCESS_GRN = "HOTEL_SUCCESS_GRN";

export const HOTEL_SINGLE_DETAIL_REQUEST = "HOTEL_SINGLE_DETAIL_REQUEST"
export const HOTEL_SINGLE_SUCCESS = "HOTEL_SINGLE_SUCCESS"

export const HOTEL_ROOMSELECT_REQUEST = "HOTEL_ROOMSELECT_REQUEST"
export const HOTEL_ROOMSELECT_SUCCESS = "HOTEL_ROOMSELECT_SUCCESS"

export const HOTEL_GALLERY_REQUEST = "HOTEL_GALLERY_REQUEST";
export const HOTEL_GALLERY_SUCCESS = "HOTEL_GALLERY_SUCCESS"


export const HOTEL_B0OKROOM_REQUESTGRN = "HOTEL_B0OKROOM_REQUESTGRN";
export const HOTEL_B0OKROOM_SUCCESSGRN = "HOTEL_B0OKROOM_SUCCESSGRN";


export const CLEAR_HOTEL_REDUCERGRN = "CLEAR_HOTEL_REDUCERGRN";
export const CLEAR_HOTEL_BLOCK_ROOM = "CLEAR_HOTEL_BLOCK_ROOM";

export const CLEAR_ONLYHOTEL_GRN = "CLEAR_ONLYHOTEL_GRN";
export const CLEAR_HOTEL_ROOMGALLERY_GRN = "CLEAR_HOTEL_ROOMGALLERY_GRN";
export const CLEAR_HOTEL_ROOM_SELECT = "CLEAR_HOTEL_ROOM_SELECT";
export const CLEAR_HOTEL_BLOCK_ROOMTYR="CLEAR_HOTEL_BLOCK_ROOMTYR"

export const CLEAR_HOTEL_SELECTED_ROOM = "CLEAR_HOTEL_SELECTED_ROOM"