
 export const jsonData=[
    ADS_HANDLER,
    PACKAGE_HANDLER,
    REQUEST_HANDLER,
    BOOKING_MANAGER,
    CUSTOMER_SUPPORT,
    CONTENT_MANAGER,
    FINANCIAL_SUBADMIN,
    USER_MANAGER,
    MARKETING_PROMOTIONS,
    ANALYTICS_SUBADMIN,
    VISA_PROCESSING,
    SECURITY_COMPLIANCE,
    LOCALIZATION_TRANSLATION,
     EVENT_HANDLER,
    COUPON_CODE_HANDLER,   
    AGENT_MANAGER
]