export const AGENT_PROFILE_LOGIN_SUCCESS = "AGENT_PROFILE_LOGIN_SUCCESS";
export const AGENT_PROFILE_LOGOUT_SUCCESS = "AGENT_PROFILE_LOGOUT_SUCCESS";
export const AGENT_PROFILE_LOGIN_REQUEST = "AGENT_PROFILE_LOGIN_REQUEST";
export const AGENT_PROFILE_LOGIN_FAILURE = "AGENT_PROFILE_LOGIN_FAILURE";