// actionTypes.js
export const FETCH_FLIGHTNAME_REQUEST = 'FETCH_FLIGHTNAME_REQUEST';
export const FETCH_FLIGHTNAME_SUCCESS = 'FETCH_FLIGHTNAME_SUCCESS';
export const FETCH_FLIGHTNAME_CLEAR = "FETCH_FLIGHTNAME_CLEAR";
// export const FETCH_FLIGHTNAME_FAILURE = 'FETCH_FLIGHTNAME_FAILURE';
